# Site settings
title: Saurabh Kulkarni
email: saurabhkulkarni2312[at]gmail.com
url: https://saurabhkulkarni2312.github.io
description: "Graduate Student at UCSD. Machine Learning, Data Enthusiast."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Saurabh Kulkarni

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/saurabhkulkarni2312/
  - title: LinkedIN
    url: https://www.linkedin.com/in/saurabhkulkarni2312

# Build settings
markdown: kramdown
permalink: pretty
